### ISSUE TITLE
Crashes when trying to monitor App Store

### ISSUE THREAD

**Issue by felipesabino** [KrauseFx/overkill-for-mac#11]
Overkill crashes when I try to add App Store to the monitored app list

1. Open overkill
2. Go to preferences
3. Click `+` to add a new app to the list
4. Select `App Store`
5. 💥 

Also

- When I open overkill again, `App Store` is not on the monitored applications list
- Same behavior happens when `App Store` is either closed or opened

---

EDIT:

Same behavior happens for other Apple Apps like `Activity Monitor` and `AirPort Utility`

**Comment by KrauseFx** [comment]
Interesting, thanks for the report. I assume this has something to do with finding the app identifier based on the plist file. I won't be able to look into this as I use overkill for iTunes and Photos only, however feel free to dive into the source code and submit a patch as a PR if you feel like it :)

**Comment by ukaytac** [comment]
Same behavior happens for Telegram Desktop too.
