### ISSUE TITLE
Please add brew cask,Thanks!

### ISSUE THREAD

**Issue by rickeylau** [KrauseFx/overkill-for-mac#15]
Please add brew cask,Thanks!

**Comment by KrauseFx** [comment]
Great idea, I don't think I'll have the time to build this, however feel free to submit a PR, and I'm happy to take a look 👍

**Comment by rinopo** [comment]
Did a PR:
https://github.com/caskroom/homebrew-cask/pull/42675

**Comment by KrauseFx** [comment]
Ha, awesome, thanks everybody 🚀
